version: '3'
services:
    openttd:
        image: ghcr.io/ghostlydilemma/openttd-jgrpp:${JGRPP_VERSION}
        ports:
            - "${HOST_PORT}:${CONTAINER_PORT}/tcp"
            - "${HOST_PORT}:${CONTAINER_PORT}/udp"
        volumes:
            - "${CONFIG_PATH}:/home/openttd/.local/share/openttd/"
        restart: always
        tty: true
        stdin_open: true
        
        environment:
            PUID: ${PUID}
            PGID: ${GUID}
            loadgame: ${FLAG_LOAD_GAME}
            # The following env variable is ignored if FLAG_LOAD_GAME is set to false or last-autosave
            savename: ${GAMESAVE_FILENAME}
            debug: "verbose"

    console:
        image: golang
        command: sleep infinity
        user: ${PUID}:${GUID}
        tty: true
        stdin_open: true